spring:
  application:
    name: qiuxun
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/qiu?useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: 123456
  session:
    timeout: 86400
    store-type: redis
  redis:
    host: 192.168.0.105
    port: 6379
    lettuce:
      pool:
        max-active: 8 #最大连接
        max-idle: 8 #最大空闲连接
        min-idle: 0 #最小空闲连接
        max-wait: 100ms #连接等待时间
    database: 1
  servlet:
    multipart:
      max-request-size: 2MB
      max-file-size: 2MB

redissonDatabase: 2

server:
  port: 8080

knife4j:
  enable: true
  openapi:
    title: 湫寻
    description: "湫寻"
    email: qqdas522@gmail.com
    concat: 邱海梦旌
    url: http://localhost:8080/doc.html
    version: v4.0
    license: Apache 2.0
    license-url: https://stackoverflow.com/
    terms-of-service-url: https://stackoverflow.com/
    group:
      test1:
        group-name: 默认分组
        api-rule: package
        api-rule-resources:
          - com.qiu.qiuxun.controller

mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: deleted # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)

aliyun:
  oss:
    endpoint:
    access-key:
    secret-key:
    bucket-name: